### ISSUE TITLE
Scaffold back button not appear in appBar

### ISSUE THREAD

**Issue by mxlandry** [ayham95/Custom-navigator#1]
Hi, 

First, thanks for this package its exactly what we need for our app! I have one small issue,  
I'm not able to make the back button appear in the appBar after a navigation. 

I'm using CustomNavigator on my Scaffold body and not recreate a Scaffold when I navigate (using Navigator.of(context).push) to a page. The back button of android device works well.

Do you have an idea why it's not refreshing the appBar ?

Thanks,
Max

**Comment by ayham95** [comment]
Hello @mxlandry!
In order for the **AppBar** to appear you need to set a **Scaffold** and an **AppBar** for every page in your navigation.

Refer to this [custom_scaffold_example](https://github.com/ayham95/Custom-navigator/tree/master/custom_scaffold_example) for more information.

Hope this helped!
I'll close the issue for now, reopen anytime i'll be here to help
Also, please add any suggestions for new features for this library, i'd be more than happy to add them.

**Comment by mxlandry** [comment]
The AppBar appear, but the backButton is not there. If a set my widget for building a Scaffold with an AppBar I have two AppBar and the second one contains the back button.

**Comment by ayham95** [comment]
Oh ok, now i got it.
I'll update the [CustomScaffold](https://github.com/ayham95/Custom-navigator/tree/master/custom_scaffold_example) so it can do exactly what you want to achieve.
Is it ok for to use the [CustomScaffold](https://github.com/ayham95/Custom-navigator/tree/master/custom_scaffold_example)? It's a widget exactly like the normal scaffold but with added functionalities.
I'll push the update in 4 hours from now.

Let me know if you're ok with it.
Thank you!

**Comment by mxlandry** [comment]
I'm using the PlatformScaffold (https://pub.dev/packages/flutter_platform_widgets) for styling the Scaffold differently on Android and iOS.
If it's possible, I would prefer to not use CustomScaffold but if it's not I will consider testing the CustomScaffold.

Thanks!

**Comment by ayham95** [comment]
I’ll be sorry to tell you that there’s no direct solution for your problem at the moment..

That being said there’s a work around.
You need to remove the **AppBar** from your main **Scaffold** and put it in every page down the widget tree instead.
This way you’ll force the AppBar to update when navigating.

Also you can refer to [custom_scaffold_example](https://github.com/ayham95/Custom-navigator/tree/master/custom_scaffold_example) to see a similar example.

I’ll make sure to add the functionality you required in the coming days. 🙏🏼

**Comment by mxlandry** [comment]
I tested out the work around and it works fine. Thanks man!
I'll check for updating the code when the functionality is ready. :)

**Comment by ayham95** [comment]
Glad it worked for you! 
I’ll close this for now.
Best wishes! 🙏🏼
