### ISSUE TITLE
CustomNavigator breaks the behavior of CupertinoSliverNavigationBar

### ISSUE THREAD

**Issue by nick-skriabin** [ayham95/Custom-navigator#10]
when using `CustomNavigator`, the behavior of `CupertinoSliverNavigationBar` breaks and those large titles are not animated on transition anymore

![ezgif-7-f6af7e31406a](https://user-images.githubusercontent.com/767890/72227121-ea028400-35a9-11ea-9991-b2ee76cf69b7.gif)

**Comment by ayham95** [comment]
Did you set your pageRoute to PageRoutes.cupertinoPageRoute ??

**Comment by nick-skriabin** [comment]
@ayham95 sure I did. unfortunately that doesn't fix anything

**Comment by nick-skriabin** [comment]
@ayham95 it seems like sometimes nested widgets doesn't have access to a proper context and that causes the problem. i've also faced the issue when bottom navigation was rendered on top of the fullscreen modal. i've managed to fix that by passing the context of a widget that is holding a `CustomNavigator` down to a widget that triggers the navigation (calls `Navigator.of(context)`)

**Comment by ayham95** [comment]
I'll close this for now.. But welcome to be opened anytime.
