### ISSUE TITLE
pushReplacement() and .pop()

### ISSUE THREAD

**Issue by domons** [ayham95/Custom-navigator#11]
Hi,
I have two problems, I use CustomScaffold and I have some tabs in bottom bar. 

**First case**: one of tab is "menu", where I have push to other pages, sth like this:
` Navigator.pushReplacement(context, MaterialPageRoute(builder: (cntx) => MyNewPage()))`
when I clicked it, screen change but bottom bar is crashed - any click on tab do nothing.

**Second case**: Changes of tabs doesn't saved history, so back button don't work between tabs of bottom bar. Also I want "close" my menu tab (back to previous tab/screen) in this way `Navigator.of(context).pop();` and I have white screen with bottom bar and this same problem like first case...

I have latest version of plugin... Any idea? ;)

**Comment by domons** [comment]
Is still there **third case**. When I go to tab, another page and another one page and I clicked any other tab in bottom bar I go to previous screen (like .pop()) not tab which I clicked...

**Comment by domons** [comment]
Any idea?

**Comment by ayham95** [comment]
I'm sorry for the late response, but can you tell me why are you using `Navigator.pushReplacement` ??

**Comment by domons** [comment]
Because I don't want to have "back arrow" in appbar. But biggest problem is third case, completely unrelated with pushReplacement method
