### ISSUE TITLE
How to keep the state of the detail page when we change another tab?

### ISSUE THREAD

**Issue by huubao2309** [ayham95/Custom-navigator#13]
At **"0" page** => Navigate to **"0" detail page** => after changing another tab => select **"0" page** again => can't keep state of **"0" detail page**

![image](https://user-images.githubusercontent.com/18402446/74410775-771c4f80-4e6c-11ea-9011-cd544838857c.png)
**=>**  
![image](https://user-images.githubusercontent.com/18402446/74410956-ce222480-4e6c-11ea-83ad-a39f7978e35c.png)
**=>** 
![image](https://user-images.githubusercontent.com/18402446/74411058-0a558500-4e6d-11ea-9a1a-06865fd5dd7f.png)
**=>**
![image](https://user-images.githubusercontent.com/18402446/74411143-3244e880-4e6d-11ea-953a-26cc3962c2d9.png)

**Comment by ayham95** [comment]
I didn't define any stack for page management.. i'm working on it at the moment!

**Comment by Maadhav** [comment]
Any update on this?

**Comment by gulmensedat** [comment]
> Any update on this?

you can solve this with stata management. I solved it using provider.

**Comment by Maadhav** [comment]
I also did the same with provider
