### ISSUE TITLE
when click bottom navigation icon, navigator does not direct push to that screen.

### ISSUE THREAD

**Issue by ahmedmirza994** [ayham95/Custom-navigator#3]
`
import 'package:capp/scopped-model/main_model.dart';
import 'package:capp/screens/about_papertale_screen.dart';
import 'package:capp/screens/dashboard_screen.dart';
import 'package:custom_navigator/custom_navigator.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  final MainModel model;

  HomeScreen({this.model});

  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();
  int _currentIndex = 0;

  @override
  Widget build(BuildContext context) {
    final tabpages = <Widget>[
      DashboardScreen(
        model: widget.model,
      ),
      AboutPaperTaleScreen(
        model: widget.model,
      ),
      AboutPaperTaleScreen(
        model: widget.model,
      ),
    ];
    return Scaffold(
      bottomNavigationBar: BottomNavigationBar(
        backgroundColor: Colors.white,
        currentIndex: _currentIndex,
        unselectedItemColor: Theme.of(context).primaryColor.withOpacity(0.5),
        selectedItemColor: Theme.of(context).primaryColor,
        items: _items,
        onTap: (index) {
          // if (index == 0) {
          navigatorKey.currentState.maybePop();
          // }
          setState(() {
            _currentIndex = index;
          });
        },
      ),
      body: CustomNavigator(
        navigatorKey: navigatorKey,
        home: tabpages[_currentIndex],
        pageRoute: PageRoutes.materialPageRoute,
      ),
    );
  }

  final _items = [
    BottomNavigationBarItem(
      icon: Icon(Icons.home),
      title: Text(''),
    ),
    BottomNavigationBarItem(
      icon: Icon(Icons.info_outline),
      title: Text(''),
    ),
    BottomNavigationBarItem(
      icon: Icon(Icons.settings),
      title: Text(''),
    ),
  ];
}
`

when click on bottom bar icon, navigator pop the route but i want to direct push to desired screen

**Comment by ayham95** [comment]
Can you please elaborate more about what you want to achieve?
Because it’s not quite clear.

**Comment by ahmedmirza994** [comment]
Hi, I am using this on three menu items. When I visit multiple views on different menus the icon press is not respective to that (related to icon) view. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30725333/66706619-718feb00-ed4e-11e9-8e84-69bdfdcd50b7.gif)
check this, problem at the end of gif,

**Comment by ayham95** [comment]
So you want multiple views on each menu item to stay active?

**Comment by ahmedmirza994** [comment]
yes

**Comment by ahmedmirza994** [comment]
the problem is when i switch one menu item to other menu item, the page under other menu item does not open directly, until it pops the all routes of first menu item

**Comment by ayham95** [comment]
Oh, ok ok that’s a valid point.
Are you using CustomScaffold? Or the normal CustomNavigator?

**Comment by ahmedmirza994** [comment]
i tried both, but the problem is same.

**Comment by ayham95** [comment]
Ok, no problem man. I’ll push a fix right away.

**Comment by ahmedmirza994** [comment]
yes please, i am working on production app and the problem need to be fixed as soon as possible

**Comment by ayham95** [comment]
Solved! Use CustomScaffold i uploaded v0.3.0
