### ISSUE TITLE
Custom navigation bottom bar 

### ISSUE THREAD

**Issue by darasat** [ayham95/Custom-navigator#7]
Good day!

How Can I integrate this plugin with a bottom navigation like this ? 

I have some errors trying this 

bottomNavigationBar: ClipRRect(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(30.0),
          topRight: Radius.circular(30.0),
        ),
        child: BottomNavigationBar(
          type: BottomNavigationBarType.fixed,
          items: [
            BottomNavigationBarItem(
              icon: Icon(
                Icons.dashboard,
                size: 30.0,
                color: Colors.black,
              ),
              title: Text(''),
            )..

Thank you

**Comment by ayham95** [comment]
I didn’t understand your problem. Do you want to integrate it with CustomScaffold or with CustomNavigator?

**Comment by darasat** [comment]
Thanks for answer me  and for this excellent library

My problem is that I want to integrate 
With a custom bottom navigation bar like this repo

https://github.com/MarcusNg/flutter_instagram_feed_ui_redesign (lib/screen/feed_screen.dart)

Using custom scaffold

 // the idea..
return CustomScaffold(
      scaffold: Scaffold(
bottomNavigationBar: ClipRRect(
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(30.0),
          topRight: Radius.circular(30.0),
        ),
        child: BottomNavigationBar(
          type: BottomNavigationBarType.fixed,
          items: [
            BottomNavigationBarItem(
              icon: Icon(
                Icons.dashboard,
                size: 30.0,
                color: Colors.black,
              ),
              title: Text(''),
            ),...
But I have some errors on 
 line 31 with asserts..


Some idea ?

Cheers from Colombia.

**Comment by ayham95** [comment]
It’s not easy customizing the CustomScaffold. But if you want i can help you implement it with CustomNavigator? How does that sound?

**Comment by darasat** [comment]
Thanks for your answers.

 I am going to close the issue now, but if I can´t find another solution I will on contact with you again.

regards.
