### ISSUE TITLE
Add 4 BottomNavigationBarItem

### ISSUE THREAD

**Issue by widiramadhan** [ayham95/Custom-navigator#9]
How to add 4 BottomNavigationBarItem ?
if I add in
`final _items = [
    BottomNavigationBarItem(icon: Icon(Icons.home), title: Text('Home')),
    BottomNavigationBarItem(icon: Icon(Icons.phone_iphone), title: Text('Tentang')),
    BottomNavigationBarItem(icon: Icon(Icons.email), title: Text('Kontak')),
    BottomNavigationBarItem(icon: Icon(Icons.person_pin), title: Text('Akun')),
  ];`
lost BottomNavigationBar in my design

**Comment by domons** [comment]
In BottomNavigationBar set `type: BottomNavigationBarType.fixed,`
